### ISSUE TITLE
nginx reverse proxy - shiny server

### ISSUE THREAD

**Issue by Stevbreu** [rocker-org/shiny#74]
I get an error after I build the Image (look at **error**)

**Error:
Starting shiny ... done
Attaching to shiny
shiny    | 
shiny    | *** warning - no files are being watched ***
shiny    | [2020-04-19T12:05:02.099] [INFO] shiny-server - Shiny Server v1.5.13.944 (Node.js v12.15.0)
shiny    | [2020-04-19T12:05:02.103] [INFO] shiny-server - Using config file "/etc/shiny-server/shiny-server.conf"
shiny    | [2020-04-19T12:05:02.205] [WARN] shiny-server - Running as root unnecessarily is a security risk! You could be running more securely as non-root.
shiny    | [2020-04-19T12:05:02.214] [INFO] shiny-server - Starting listener on http://[::]:3838**

-----------------------------------------------------
```
That is my docker-compose.yml:
version: "3.0"

services:
  shiny:
    container_name: shiny
    # To build the image locally, comment out "image" below, and uncomment
    # "build" and the lines indented under it.
    # image: rocker/shiny
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    # Setting this to something other than 'root' will cause shiny apps not to
    # run on the localhost:80 "Welcome to Shiny" diagnostics page mentioned
    # below.
    user: 'root'
    # Uncomment the lines below to disable application logs STDOUT output
    # environment:
    #   - APPLICATION_LOGS_TO_STDOUT=false
    ports:
            - '3838'
    networks:
      - nextcloud_nextcloud_network
    environment:
      - VIRTUAL_HOST=shiny.*****.eu
        #- VIRTUAL_NETWORK=nginx-proxy
        #- VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=shiny.*****.eu
      - LETSENCRYPT_EMAIL=*****@****.de
    volumes:
      - 'shiny_logs:/var/log/shiny-server'
      # Comment the line below out for initial testing. With it commented out,
      # going to localhost:80 in one's web browser will show a "Welcome to
      # Shiny Server!" diagnostics page.
      - ./mountpoints/apps:/srv/shiny-server'

networks:
  nextcloud_nextcloud_network:
          external: true
volumes:
  shiny_logs:
  apps:
```
-----------------------------------------------------------
I have a nginx-reverse-proxy and my rstudio server works great,
but I cannot get an access to my shiny server. 

Best regards
Steven
