### ISSUE TITLE
Can't read environment variable set in docker-compose

### ISSUE THREAD

**Issue by Chrisjb** [rocker-org/shiny#76]
Hi, 
I'm having trouble accessing environment variables set in docker-compose. I would expect to be able to run my containerised shiny app and use `Sys.getenv('MY_ENV_VARIABLE')` in my `app.R` file to get the variable set in my docker-compose.yaml.

see [my repo](https://github.com/Chrisjb/rshiny-env-variable) for a minimal example of what I mean. In docker-compose I have:

```yaml
version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    user: 'root'
    volumes: 
      - .:/app
    environment:
      MY_ENV_VARIABLE: 'HELLO'
    ports: 
      - 3838:3838
```

and in app.R:
```R
library(shiny)

ui <- fluidPage(

    # Application title
    titlePanel("Environment variable example:"),
    
    mainPanel(
          h1(class='display-1', "Env variable: ", textOutput('x'))
        )
)

# Define server logic required to draw a histogram
server <- function(input, output) {

    output$x <- renderText({
       Sys.getenv('MY_ENV_VARIABLE')
    })
}

# Run the application 
shinyApp(ui = ui, server = server)
```

and Dockerfile.dev:
```
# get shiny serves plus tidyverse packages image
FROM rocker/shiny-verse:latest

# system libraries of general use
RUN echo 'deb http://deb.debian.org/debian bullseye main' > /etc/apt/sources.list
RUN apt-get update && apt-get install -y \
    libpq-dev \
    libcurl4-openssl-dev \
    libgdal-dev \
    libgeos-dev \
    libproj-dev \
    libudunits2-dev \
    libssh2-1-dev \
    libcairo2-dev \
    sudo

# copy the app to the image
COPY ./env-variable/app.R /srv/shiny-server/

EXPOSE 3838

# allow permission
RUN sudo chown -R shiny:shiny /srv/shiny-server

# run app
CMD ["/usr/bin/shiny-server.sh"]
```

Any help on how to get shiny to read environment variables from docker-compose? I will also need this when deploying to aws EC2 and setting my env variables there.

Thanks in advance!

Chris
